# This is a basic workflow to help you get started with Actions

name: Build Site

# Controls when the action will run. 
on:
  # Triggers the workflow on push of repository
  push:
    branches: [ main ]
  # Can add a schedule cron of when to run action but leaving this commented out for now
  schedule:
    - cron: '0 * * * *'  # every hour
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
    # PHP GitHub Action created by https://github.com/nanasess
    - uses: actions/checkout@master
    - uses: nanasess/setup-php@master
      with:
        php-version: '7.4'
    # This triggers our php file we created before
    - run: php ./build.php
    - name: Commit published HTML
      id: commit
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        if [ -n "$(git status --porcelain index.html)" ]; then
          git add index.html
          git commit -m "[ci skip] chore(index.html): update resume page"
          echo ::set-output name=exit_code::0
        else
          echo ::set-output name=exit_code::1
        fi
    - name: Push changes
      uses: ad-m/github-push-action@master
      if: steps.commit.outputs.exit_code == 0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
